### ISSUE TITLE
Generation of ontology is not 100% deterministic

### ISSUE THREAD

**Issue by jbulow** [BrickSchema/Brick#324]
The same brick source generate slightly different `Brick.ttl` files on each run. The order of shape constraints are randomized. This is a minor problem but causes some confusion when inspecting the diff on that has been updated between revisions.

**Comment by gtfierro** [comment]
Thanks for bringing this up! My impression is that the ultimate goal is to be able to more effectively compare the differences between revisions; making the ontology serialization deterministic is one way of achieving this, but it is not the only way. While the proposed fix in #325 does work, it is dependent on the order of function calls in `generate_brick.py` and deterministic iteration through dictionaries and other data structures used during the Brick ontology generation process. This feels a little too brittle too my liking, and I wonder if we can come up with a more robust approach.

What do you think of producing an alternative textual representation of Brick that facilitates diffs? The naive option of serializing Brick into the N-Triples format and then sorting the file lexicographically would fall prey to the same issue that you are fixing above. Instead, we could produce a TOML or YAML file with all of the properties of each Brick entity listed below. This would remove all blank nodes from the representation and only preserve the actual IRIs and literals in Brick. Result would look something like...

```
Sensor:
  definition: "text definition here"
  subclasses:
    - Temperature_Sensor
    - etc...
Temperature_Sensor:
   constraints:
       - property:
             path: brick:isPointOf
             class: Equipment
```

The components could be consistently ordered, and there could be consistent rules for turning the different RDF constructs into this representation, where traditional diff tools would be more effective. Thoughts?
