### ISSUE TITLE
RFC: Structured Tag Generation

### ISSUE THREAD

**Issue by berkoben** [BrickSchema/Brick#36]
**Background:**
The current means of defining Brick tags and Tagsets is highly repetitive, does not enforce consistency / non-duplication, nor does it facilitate generating tag[set] documentation.  

This is a problem when trying to use Brick in real applications.  

**Objective**
To specify a concise method for defining tags and tagsets that allows machine-generation of an internally consistent ontology of tags and tagsets with non-overlapping semantic meaning (i.e. no two tags define exactly the same concept).  

**Discussion:**
One of the most powerful features of Brick is that it provides a means for attaching a precise semantic definition to a piece of data that persists across the context where it is found.  For example, a point tagged  with zone_air_temperature_sensor (ZATS) is known to be the ambient air temperature in the region of space measured by the sensor.  This definition is the same whether the point is obtained from a thermostat or a light fixture (yes, light fixtures sometimes have temp sensors).  

Conceptually, the ZATS tagset is created by combining concepts from disjoint sets to create a more complex concept: <location>_<media>_<measurement type>_<point type>.  This is very powerful because it allows a virtually infinite number of meaningful composite concepts to be created and understood without individually defining each one.  To be more specific about the meaning here:  If each of the individual tags in a tag set has a precise definition, the precise meaning of a tagset will, more often than not, be easy to infer.  (Note: for this to be strictly true all tags must be unique, single words, combinedWithoutSpaces, or make use of a reserved-character-delimiter).

If we are also willing to use the class hierarchies in Brick (pointType, MeasurementType, Equipment, Location, etc...)  to enforce a limited grammar, we could write code to generate internally consistent groups of tagsets very concisely around a central concept.  With the right structure this could be done modularly and flexibly in ways that map to conceptual similarities.  An example: 

Take the concept of temperature.  We could create code that looks something like this: 

```
Temperature:
  group:
    media: [Air]
    types: [Zone,Outside, Discharge, return]
  group:
    media: [Water]
    modifiers: [hot, chilled]
    types: [discharge, return]

would yield: 

Zone_Air_Temperature
Outside_Air_Temperature
Discharge_Air_Temperature
Return_Air_Temperature
Discharge_Hot_Water_Temperature
Discharge_Chilled_Water_Temperature
Return_Hot_Water_Temperature
Return_Chilled_Water_Temperature
```
in the above, we are able to take multiple well-defined tags, and use simple rules to mechanically create tagsets. In the above example, we create groups for air and water because the concepts we want to produce for the two media are divergent.  However, we could easily modify this code if we were monitoring, say an indoor-outdoor pool, to include "water" in the media list of the first group and we would get the following additional tags:

Zone_Water_Temperature
Outside_Water_Temperature
Discharge_Water_Temperature
Return_Water_Temperature

This would allow you to get all of the core concepts written.  A parser for this structured file could ensure that no tagsets appear twice and that only pre-defined tags are used. 

To be added in future posts:  mapping to point types and equipment.

**Comment by gtfierro** [comment]
Just putting the note here that I have an implementation of this that I'm working on and can post soon

**Comment by berkoben** [comment]
Thanks!  I'm writing up comments on your readme right now

**Comment by gtfierro** [comment]
**Note to all**: There is a preliminary implementation of this at the [gabe-efforts branch](https://github.com/BuildSysUniformMetadata/Brick/tree/gabe-efforts/src). It is a work in progress.

First of all, I want to enumerate my support for this idea. Having a structured means of generating tagsets for Brick means that we can be more consistent and complete in its definition, and more easily expand and extend the Brick ontology.  The documents describe the compositions of tags into tagsets, as well as a few of the "meta" relationships between tagsets (such as synonyms).

When these documents are compiled into the Brick ontology, we can make sure that the tagsets are explicitly constructed of the actual tags (e.g. "Outside Air Temperature Sensor" has tags "outside" "air" "temperature" and "sensor").  Keeping these tags consistent has been an issue in the past, but I think its a powerful way of managing the complexity and size of the full class hierarchy. People want to know what they have in their building relating to "discharge air"; the tags can help find what the correct classes to use are.

After giving it some thought, I think there's a couple ways we will want to phrase these documents: a measurement-based view and a class-based view.

## Class-based View

This is a very traditional and straightforward enumeration of a class hierarchy. 

### Overview

Example: 

```yaml
Point:
    subclasses:
        Alarm:
        Command:
        Meter:
        Sensor:
```

or

```yaml
Air Handler Unit:
    synonyms: [AHU]
    subclasses:
        Roof-Top Unit:
            synonyms: [RTU]
```

The advantage here is it is easy to see what the class structure is. As we move down the hierarchy, the equipment becomes more specific in terms of its functionality. There's a role here for something like a `uses` relationship to identify which tagsets are commonly associated with a piece of equipment. For example:

```yaml
Variable Air Volume Box:
    synonyms: [VAV]
    uses:
        - Zone Air Temperature Sensor
        - Discharge Air Temperature Sensor
        - Zone Air Temperature Setpoint
        - Discharge Air Damper
        - Return Air Damper
        - Return Fan
```

I don't quite want to get into the question of "mandatory" vs "optional" attributes yet; this is merely to illustrate the point that being explicit about the class hierarchy dovetails nicely with being able to do this sort of construction.

### Discussion

The problem, as @berkoben has pointed out, is that its difficult to be consistent across sibling branches of the class hierarchy. A concrete example of this is for the concept of temperature above. Within the "Temperature" context, I have both Air temperature and Water temperature. Within each of those, I have discharge and return but also some other types. Further, I have both sensors and setpoints (and differential setpoints, and reset commands, alarms, etc). If we stick with the class-based view, then we're stuck with being explicit about that:

```yaml
Point:
    subclasses:
        Sensor:
            types:
                Temperature:
                    media:
                        - Air:
                               types: [Outside, Return, Discharge]
                        - Water:
                               types: [Return, Discharge]
        Setpoint:
            types:
                Temperature:
                    media:
                        - Air:
                               types: [Discharge]
                        - Water:
                               types: [Discharge]
        Alarm:
            types:
                Temperature:
                    media:
                        - Air:
                               types: [Outside, Return, Discharge]
                        - Water:
                               types: [Return, Discharge]
```

In this case, we have a collection of points (sensors, setpoints, alarms, commands, etc) that are associated with a particular context.

## Measurement-based View

This is what I'm terming the construction that @berkoben offered above. We build the tagsets off of their contexts, which offers a more natural grouping of the points and possibly helps make it more succinct and consistent.

### Overview

```yaml
Temperature:
    - media: Air 
      classes:
          - Sensor:
                 types: [Zone, Outside, Discharge, Return]
          - Setpoint:
                 types: [Zone, Discharge]
    - media: Water
       modifiers: [Hot, Chilled, Condenser]
       types: [Discharge, Return]
       classes: [Sensor, Setpoint]
```

would generate

```
Air Temperature Sensor
Air Temperature Setpoint
Zone Air Temperature Sensor
Outside Air Temperature Sensor
Discharge Air Temperature Sensor
Return Air Temperature Sensor
Zone Air Temperature Setpoint
Discharge Air Temperature Setpoint

Water Temperature Sensor
Water Temperature Setpoint
Hot Water Temperature Sensor
Hot Water Temperature Setpoint
Chilled Water Temperature Sensor
Chilled Water Temperature Setpoint
Condenser Water Temperature Sensor
Condenser Water Temperature Setpoint

Discharge Chilled Water Temperature Sensor
Discharge Chilled Water Temperature Setpoint
Discharge Condenser Water Temperature Sensor
Discharge Condenser Water Temperature Setpoint
Return Chilled Water Temperature Sensor
Return Chilled Water Temperature Setpoint
Return Condenser Water Temperature Sensor
Return Condenser Water Temperature Setpoint
```

### Discussion

I think this makes a lot of sense for the point classes, because they are all grouped around measurements of media (e.g. temperature of water, CO2 content of air, etc). However, this isn't as great for the equipment hierarchy, because a piece of equipment will span several media. For example, a chiller will affect air, but uses water to do so, so it doesn't cleanly fit into either the Air or Water media of a Temperature context.

The disadvantage of this approach is it can start to exhibit some of the "sibling duplication". In my example above,  it doesn't make sense to have Outside and Return air setpoints, so I had to duplicate the `types` field across the classes for the Air Temperature context.
